export const products = [
  {
    id: "1",
    title: "Wireless Noise Cancelling Headphones with 30-Hour Battery Life",
    brand: "SoundMaster",
    model: "WH-1000XM4",
    description:
      "Experience premium sound quality with industry-leading noise cancellation technology. These wireless headphones deliver exceptional audio performance with a comfortable over-ear design and long-lasting battery life.",
    price: 299.99,
    originalPrice: 349.99,
    discount: 14,
    rating: 4.8,
    reviewCount: 3245,
    image: "/placeholder.svg?height=300&width=300",
    features: [
      "Industry-leading noise cancellation",
      "30-hour battery life with quick charging",
      "Touch sensor controls for easy operation",
      "Speak-to-chat technology automatically pauses playback when you speak",
      "Wearing detection pauses playback when headphones are removed",
    ],
    material: "Premium plastic and leather",
    weight: "8.96 oz (254g)",
  },
  {
    id: "2",
    title: "Ultra HD 4K Smart TV with Voice Control, 55-inch",
    brand: "VisionPlus",
    model: "VP-55UHD",
    description:
      "Transform your home entertainment with this stunning 4K Ultra HD Smart TV. Featuring advanced voice control, HDR technology, and a sleek design, this TV delivers exceptional picture quality and smart functionality.",
    price: 499.99,
    originalPrice: 649.99,
    discount: 23,
    rating: 4.6,
    reviewCount: 1876,
    image: "/placeholder.svg?height=300&width=300",
    features: [
      "4K Ultra HD resolution (3840 x 2160)",
      "HDR technology for enhanced contrast and color",
      "Voice control compatible with Alexa and Google Assistant",
      "Built-in streaming apps including Netflix, Prime Video, and more",
      "Multiple HDMI and USB ports for connectivity",
    ],
    material: "Metal frame with glass screen",
    weight: "35.2 lbs (16kg)",
  },
  {
    id: "3",
    title: "Professional Blender with Variable Speed Control, 64 oz",
    brand: "BlendMaster",
    model: "BM-Pro750",
    description:
      "This professional-grade blender features a powerful motor and variable speed control to handle even the toughest ingredients. Perfect for smoothies, soups, nut butters, and more.",
    price: 399.99,
    originalPrice: 499.99,
    discount: 20,
    rating: 4.9,
    reviewCount: 2543,
    image: "/placeholder.svg?height=300&width=300",
    features: [
      "2.2 HP motor for powerful blending performance",
      "Variable speed control and pulse feature",
      "64 oz BPA-free container",
      "Hardened stainless-steel blades",
      "Self-cleaning capability with drop of dish soap and warm water",
    ],
    material: "Die-cast metal base with BPA-free plastic container",
    weight: "11.5 lbs (5.2kg)",
  },
  {
    id: "4",
    title: "Ergonomic Office Chair with Lumbar Support and Adjustable Headrest",
    brand: "ComfortPro",
    model: "CP-Ergo100",
    description:
      "Designed for all-day comfort, this ergonomic office chair features adjustable lumbar support, a breathable mesh back, and customizable settings to help maintain proper posture during long work sessions.",
    price: 249.99,
    originalPrice: 299.99,
    discount: 17,
    rating: 4.7,
    reviewCount: 1432,
    image: "/placeholder.svg?height=300&width=300",
    features: [
      "Adjustable lumbar support for lower back comfort",
      "Breathable mesh back for temperature regulation",
      "Adjustable headrest, armrests, and seat height",
      "Tilt tension control and lockable recline",
      "360-degree swivel and smooth-rolling casters",
    ],
    material: "Mesh, high-density foam, and reinforced nylon",
    weight: "35 lbs (15.9kg)",
  },
  {
    id: "5",
    title: "Smart Home Security Camera System with Night Vision, 3-Pack",
    brand: "SecureView",
    model: "SV-Pro3",
    description:
      "Keep your home secure with this advanced security camera system. Featuring HD video, night vision, motion detection, and two-way audio, these cameras connect to your smartphone for real-time monitoring from anywhere.",
    price: 199.99,
    originalPrice: 249.99,
    discount: 20,
    rating: 4.5,
    reviewCount: 987,
    image: "/placeholder.svg?height=300&width=300",
    features: [
      "1080p HD video quality for clear footage",
      "Night vision up to 30 feet in complete darkness",
      "Motion detection with customizable activity zones",
      "Two-way audio for remote communication",
      "Weather-resistant design for indoor and outdoor use",
    ],
    material: "Weather-resistant plastic",
    weight: "2.2 lbs (1kg) per camera",
  },
  {
    id: "6",
    title: "Robot Vacuum Cleaner with Mapping Technology and Self-Emptying Base",
    brand: "CleanBot",
    model: "CB-X8Pro",
    description:
      "This advanced robot vacuum cleaner uses smart mapping technology to efficiently clean your home. With powerful suction, a self-emptying base, and app control, it makes maintaining clean floors effortless.",
    price: 599.99,
    originalPrice: 799.99,
    discount: 25,
    rating: 4.7,
    reviewCount: 1654,
    image: "/placeholder.svg?height=300&width=300",
    features: [
      "Smart mapping technology creates efficient cleaning paths",
      "Self-emptying base holds up to 60 days of dirt and debris",
      "3-stage cleaning system with 2500Pa suction power",
      "Multi-surface brushes work on carpets and hard floors",
      "App control with scheduling and customizable cleaning zones",
    ],
    material: "High-impact plastic with rubber brushes",
    weight: "7.8 lbs (3.5kg)",
  },
  {
    id: "7",
    title: "Stainless Steel Air Fryer with Digital Display, 5.8 Quart",
    brand: "CrispMaster",
    model: "CM-AF580",
    description:
      "Enjoy healthier fried foods with this large-capacity air fryer. Using little to no oil, it delivers crispy exteriors and tender interiors for your favorite foods, with easy digital controls and preset cooking programs.",
    price: 129.99,
    originalPrice: 159.99,
    discount: 19,
    rating: 4.8,
    reviewCount: 2187,
    image: "/placeholder.svg?height=300&width=300",
    features: [
      "5.8-quart capacity feeds 3-5 people",
      "8 preset cooking programs for easy operation",
      "Digital touchscreen with precise temperature control",
      "Dishwasher-safe removable basket and drawer",
      "Uses up to 85% less oil than traditional frying",
    ],
    material: "Stainless steel exterior with non-stick cooking basket",
    weight: "13.2 lbs (6kg)",
  },
  {
    id: "8",
    title: "Portable Bluetooth Speaker with 24-Hour Playtime and Waterproof Design",
    brand: "SoundWave",
    model: "SW-Extreme",
    description:
      "Take your music anywhere with this rugged, waterproof Bluetooth speaker. Delivering powerful 360° sound and featuring a long-lasting battery, it's perfect for outdoor adventures, beach trips, and pool parties.",
    price: 149.99,
    originalPrice: 179.99,
    discount: 17,
    rating: 4.6,
    reviewCount: 1543,
    image: "/placeholder.svg?height=300&width=300",
    features: [
      "Powerful 360° sound with deep bass",
      "IPX7 waterproof rating for pool and beach use",
      "24-hour battery life on a single charge",
      "Built-in power bank to charge your devices",
      "Durable, drop-resistant design for outdoor use",
    ],
    material: "Rugged fabric and silicone",
    weight: "2.5 lbs (1.1kg)",
  },
  {
    id: "9",
    title: "Digital Drawing Tablet with Pressure-Sensitive Pen, 10-inch",
    brand: "ArtCanvas",
    model: "AC-Pro10",
    description:
      "Express your creativity with this professional drawing tablet. Featuring a pressure-sensitive pen, customizable shortcut keys, and compatibility with major design software, it's perfect for digital artists and graphic designers.",
    price: 249.99,
    originalPrice: 299.99,
    discount: 17,
    rating: 4.7,
    reviewCount: 876,
    image: "/placeholder.svg?height=300&width=300",
    features: [
      "8192 levels of pressure sensitivity for precise control",
      "10-inch active drawing area with anti-glare surface",
      "Battery-free pen requires no charging",
      "8 customizable shortcut keys for efficient workflow",
      "Compatible with Windows, Mac, and major design software",
    ],
    material: "Aluminum and plastic",
    weight: "1.5 lbs (0.7kg)",
  },
  {
    id: "10",
    title: "Smart Fitness Watch with Heart Rate Monitor and GPS",
    brand: "FitTech",
    model: "FT-Pulse",
    description:
      "Track your fitness goals with this advanced smartwatch. Featuring heart rate monitoring, built-in GPS, sleep tracking, and water resistance, it helps you stay motivated and monitor your progress throughout your fitness journey.",
    price: 199.99,
    originalPrice: 249.99,
    discount: 20,
    rating: 4.5,
    reviewCount: 1298,
    image: "/placeholder.svg?height=300&width=300",
    features: [
      "24/7 heart rate monitoring with alerts",
      "Built-in GPS for accurate pace and distance tracking",
      "Water-resistant to 50 meters for swimming",
      "Sleep tracking with insights for better rest",
      "7-day battery life with typical use",
    ],
    material: "Aluminum case with silicone band",
    weight: "1.6 oz (45g)",
  },
  {
    id: "11",
    title: "Professional DSLR Camera with 24-70mm Lens Kit",
    brand: "OptiView",
    model: "OV-D850",
    description:
      "Capture stunning photos and videos with this professional DSLR camera. Featuring a high-resolution sensor, 4K video capability, and a versatile lens kit, it's perfect for photographers of all skill levels.",
    price: 1299.99,
    originalPrice: 1499.99,
    discount: 13,
    rating: 4.9,
    reviewCount: 754,
    image: "/placeholder.svg?height=300&width=300",
    features: [
      "45.7MP full-frame sensor for exceptional detail",
      "4K UHD video recording at 30fps",
      "Professional 24-70mm f/2.8 lens included",
      "Advanced autofocus system with 153 focus points",
      "Weather-sealed body for shooting in challenging conditions",
    ],
    material: "Magnesium alloy body",
    weight: "2.2 lbs (1kg) body only",
  },
  {
    id: "12",
    title: "Espresso Machine with Built-in Grinder and Milk Frother",
    brand: "BrewMaster",
    model: "BM-Barista",
    description:
      "Enjoy cafe-quality espresso at home with this all-in-one espresso machine. Featuring a built-in grinder, precise temperature control, and a professional milk frother, it allows you to craft your favorite espresso-based drinks with ease.",
    price: 599.99,
    originalPrice: 699.99,
    discount: 14,
    rating: 4.7,
    reviewCount: 932,
    image: "/placeholder.svg?height=300&width=300",
    features: [
      "Built-in conical burr grinder with 18 settings",
      "PID temperature control for optimal extraction",
      "Professional steam wand for silky microfoam",
      "Programmable shot volumes and temperature",
      "Quick heat-up time of 3 seconds",
    ],
    material: "Stainless steel with thermal block heating system",
    weight: "23 lbs (10.4kg)",
  },
  {
    id: "13",
    title: "Wireless Gaming Mouse with RGB Lighting and 25,000 DPI",
    brand: "GameTech",
    model: "GT-Ultra",
    description:
      "Gain a competitive edge with this high-performance wireless gaming mouse. Featuring an ultra-precise sensor, customizable RGB lighting, and programmable buttons, it delivers the speed and accuracy serious gamers demand.",
    price: 99.99,
    originalPrice: 129.99,
    discount: 23,
    rating: 4.8,
    reviewCount: 1576,
    image: "/placeholder.svg?height=300&width=300",
    features: [
      "25,000 DPI optical sensor for ultimate precision",
      "Ultra-low latency wireless connection",
      "Up to 70 hours of battery life",
      "8 programmable buttons for custom commands",
      "Customizable RGB lighting with 16.8 million colors",
    ],
    material: "High-grade plastic with textured grips",
    weight: "3.5 oz (99g)",
  },
  {
    id: "14",
    title: "Smart Thermostat with Voice Control and Energy Saving Features",
    brand: "EcoTemp",
    model: "ET-Smart",
    description:
      "Save energy and maintain optimal comfort with this smart thermostat. It learns your schedule, adjusts to your preferences, and can be controlled remotely via smartphone or voice commands.",
    price: 199.99,
    originalPrice: 249.99,
    discount: 20,
    rating: 4.6,
    reviewCount: 1243,
    image: "/placeholder.svg?height=300&width=300",
    features: [
      "Learning capability adapts to your schedule",
      "Remote control via smartphone app",
      "Voice control with Alexa and Google Assistant",
      "Energy usage reports and saving suggestions",
      "Geofencing for automatic home/away settings",
    ],
    material: "Glass and metal",
    weight: "8.5 oz (241g)",
  },
  {
    id: "15",
    title: "Cordless Stick Vacuum with HEPA Filtration, 60-Minute Runtime",
    brand: "CleanSweep",
    model: "CS-UltraLite",
    description:
      "Keep your home spotless with this powerful cordless vacuum. Featuring a lightweight design, HEPA filtration, and long battery life, it effortlessly cleans all floor types and reaches tight spaces with ease.",
    price: 299.99,
    originalPrice: 349.99,
    discount: 14,
    rating: 4.7,
    reviewCount: 1865,
    image: "/placeholder.svg?height=300&width=300",
    features: [
      "Powerful digital motor with 150AW suction",
      "HEPA filtration captures 99.97% of particles",
      "60-minute runtime on a single charge",
      "Converts to handheld for versatile cleaning",
      "LED headlights to illuminate dust in dark areas",
    ],
    material: "Durable plastic with metal wand",
    weight: "6.8 lbs (3.1kg)",
  },
]

